#!/bin/bash

set -e -x

echo "Creating release dir..."
mkdir -p release

echo "Creating linux/386 binary..."
GOOS=linux GOARCH=386 go build -o clownfish
tar zcvf release/clownfish-linux-32bit.tgz clownfish

echo "Creating linux/amd64 binary..."
GOOS=linux GOARCH=amd64 go build -o clownfish
tar zcvf release/clownfish-linux-64bit.tgz clownfish

echo "Creating linux/ARMv5 binary..."
GOOS=linux GOARCH=arm GOARM=5 go build -o clownfish
tar zcvf release/clownfish-linux-arm-v5.tgz clownfish

echo "Creating linux/ARMv6 binary..."
GOOS=linux GOARCH=arm GOARM=6 go build -o clownfish
tar zcvf release/clownfish-linux-arm-v6.tgz clownfish

rm clownfish
