#!/bin/bash

set -e -x

rm -rf release

echo "Creating release dir..."
mkdir -p release

gox -output="./release/{{.Dir}}-{{.OS}}-{{.Arch}}"

cd release
for f in $(find . -type f) ; do
  tar -cvzf "${f}.tgz" "$f"
  rm "$f"
done


